---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  workflow_call:

jobs:
  pr_labels:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: 🏷 Verify PR has a valid label
        uses: jesusvasquez333/verify-pr-label-action@657d111bbbe13e22bbd55870f1813c699bde1401 # v1.4.0
        with:
          pull-request-number: "${{ github.event.pull_request.number }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: >-
            breaking-change, bugfix, documentation, enhancement,
            refactor, performance, new-feature, maintenance, ci, dependencies
          disable-reviews: true
